# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI Files/timerwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 248)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GarageTracker.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushNightclub = QtWidgets.QPushButton(self.centralwidget)
        self.pushNightclub.setObjectName("pushNightclub")
        self.verticalLayout_3.addWidget(self.pushNightclub)
        self.pushBunker = QtWidgets.QPushButton(self.centralwidget)
        self.pushBunker.setObjectName("pushBunker")
        self.verticalLayout_3.addWidget(self.pushBunker)
        self.pushCoke = QtWidgets.QPushButton(self.centralwidget)
        self.pushCoke.setObjectName("pushCoke")
        self.verticalLayout_3.addWidget(self.pushCoke)
        self.pushMeth = QtWidgets.QPushButton(self.centralwidget)
        self.pushMeth.setObjectName("pushMeth")
        self.verticalLayout_3.addWidget(self.pushMeth)
        self.pushCash = QtWidgets.QPushButton(self.centralwidget)
        self.pushCash.setObjectName("pushCash")
        self.verticalLayout_3.addWidget(self.pushCash)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressNightclub = QtWidgets.QProgressBar(self.centralwidget)
        self.progressNightclub.setProperty("value", 24)
        self.progressNightclub.setObjectName("progressNightclub")
        self.verticalLayout_2.addWidget(self.progressNightclub)
        self.progressBunker = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBunker.setProperty("value", 24)
        self.progressBunker.setObjectName("progressBunker")
        self.verticalLayout_2.addWidget(self.progressBunker)
        self.progressCoke = QtWidgets.QProgressBar(self.centralwidget)
        self.progressCoke.setProperty("value", 24)
        self.progressCoke.setObjectName("progressCoke")
        self.verticalLayout_2.addWidget(self.progressCoke)
        self.progressMeth = QtWidgets.QProgressBar(self.centralwidget)
        self.progressMeth.setProperty("value", 24)
        self.progressMeth.setObjectName("progressMeth")
        self.verticalLayout_2.addWidget(self.progressMeth)
        self.progressCash = QtWidgets.QProgressBar(self.centralwidget)
        self.progressCash.setProperty("value", 24)
        self.progressCash.setObjectName("progressCash")
        self.verticalLayout_2.addWidget(self.progressCash)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNightclubRem = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNightclubRem.sizePolicy().hasHeightForWidth())
        self.labelNightclubRem.setSizePolicy(sizePolicy)
        self.labelNightclubRem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNightclubRem.setObjectName("labelNightclubRem")
        self.verticalLayout.addWidget(self.labelNightclubRem)
        self.labelBunkerRem = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBunkerRem.sizePolicy().hasHeightForWidth())
        self.labelBunkerRem.setSizePolicy(sizePolicy)
        self.labelBunkerRem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBunkerRem.setObjectName("labelBunkerRem")
        self.verticalLayout.addWidget(self.labelBunkerRem)
        self.labelCokeRem = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCokeRem.sizePolicy().hasHeightForWidth())
        self.labelCokeRem.setSizePolicy(sizePolicy)
        self.labelCokeRem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCokeRem.setObjectName("labelCokeRem")
        self.verticalLayout.addWidget(self.labelCokeRem)
        self.labelMethRem = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMethRem.sizePolicy().hasHeightForWidth())
        self.labelMethRem.setSizePolicy(sizePolicy)
        self.labelMethRem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMethRem.setObjectName("labelMethRem")
        self.verticalLayout.addWidget(self.labelMethRem)
        self.labelCashRem = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCashRem.sizePolicy().hasHeightForWidth())
        self.labelCashRem.setSizePolicy(sizePolicy)
        self.labelCashRem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCashRem.setObjectName("labelCashRem")
        self.verticalLayout.addWidget(self.labelCashRem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReset = QtWidgets.QMenu(self.menubar)
        self.menuReset.setObjectName("menuReset")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset_All_Timers = QtWidgets.QAction(MainWindow)
        self.actionReset_All_Timers.setObjectName("actionReset_All_Timers")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReset_All_Timers_2 = QtWidgets.QAction(MainWindow)
        self.actionReset_All_Timers_2.setObjectName("actionReset_All_Timers_2")
        self.actionNightclub = QtWidgets.QAction(MainWindow)
        self.actionNightclub.setObjectName("actionNightclub")
        self.actionBunker = QtWidgets.QAction(MainWindow)
        self.actionBunker.setObjectName("actionBunker")
        self.actionCoke = QtWidgets.QAction(MainWindow)
        self.actionCoke.setObjectName("actionCoke")
        self.actionMeth = QtWidgets.QAction(MainWindow)
        self.actionMeth.setObjectName("actionMeth")
        self.actionCash = QtWidgets.QAction(MainWindow)
        self.actionCash.setObjectName("actionCash")
        self.menuFile.addAction(self.actionQuit)
        self.menuReset.addAction(self.actionReset_All_Timers_2)
        self.menuReset.addAction(self.actionNightclub)
        self.menuReset.addAction(self.actionBunker)
        self.menuReset.addAction(self.actionCoke)
        self.menuReset.addAction(self.actionMeth)
        self.menuReset.addAction(self.actionCash)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuReset.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtGTATimer"))
        self.pushNightclub.setText(_translate("MainWindow", "Nightclub"))
        self.pushBunker.setText(_translate("MainWindow", "Bunker"))
        self.pushCoke.setText(_translate("MainWindow", "Coke"))
        self.pushMeth.setText(_translate("MainWindow", "Meth"))
        self.pushCash.setText(_translate("MainWindow", "Cash"))
        self.labelNightclubRem.setText(_translate("MainWindow", "TextLabel"))
        self.labelBunkerRem.setText(_translate("MainWindow", "TextLabel"))
        self.labelCokeRem.setText(_translate("MainWindow", "TextLabel"))
        self.labelMethRem.setText(_translate("MainWindow", "TextLabel"))
        self.labelCashRem.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuReset.setTitle(_translate("MainWindow", "Reset"))
        self.actionReset_All_Timers.setText(_translate("MainWindow", "Reset All Timers"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionReset_All_Timers_2.setText(_translate("MainWindow", "Reset All Timers"))
        self.actionNightclub.setText(_translate("MainWindow", "Reset Nightclub"))
        self.actionBunker.setText(_translate("MainWindow", "Bunker"))
        self.actionCoke.setText(_translate("MainWindow", "Coke"))
        self.actionMeth.setText(_translate("MainWindow", "Meth"))
        self.actionCash.setText(_translate("MainWindow", "Cash"))
