# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI Files/vehicle_edit.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogVehicleEdit(object):
    def setupUi(self, DialogVehicleEdit):
        DialogVehicleEdit.setObjectName("DialogVehicleEdit")
        DialogVehicleEdit.resize(458, 151)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogVehicleEdit.sizePolicy().hasHeightForWidth())
        DialogVehicleEdit.setSizePolicy(sizePolicy)
        DialogVehicleEdit.setMinimumSize(QtCore.QSize(458, 150))
        DialogVehicleEdit.setMaximumSize(QtCore.QSize(458, 151))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GarageTracker.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogVehicleEdit.setWindowIcon(icon)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(DialogVehicleEdit)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkWishlist = QtWidgets.QCheckBox(DialogVehicleEdit)
        self.checkWishlist.setObjectName("checkWishlist")
        self.verticalLayout.addWidget(self.checkWishlist)
        self.checkPegasus = QtWidgets.QCheckBox(DialogVehicleEdit)
        self.checkPegasus.setObjectName("checkPegasus")
        self.verticalLayout.addWidget(self.checkPegasus)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkOwned = QtWidgets.QCheckBox(DialogVehicleEdit)
        self.checkOwned.setObjectName("checkOwned")
        self.verticalLayout_2.addWidget(self.checkOwned)
        self.checkDelete = QtWidgets.QCheckBox(DialogVehicleEdit)
        self.checkDelete.setObjectName("checkDelete")
        self.verticalLayout_2.addWidget(self.checkDelete)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkInsured = QtWidgets.QCheckBox(DialogVehicleEdit)
        self.checkInsured.setObjectName("checkInsured")
        self.verticalLayout_3.addWidget(self.checkInsured)
        self.checkModified = QtWidgets.QCheckBox(DialogVehicleEdit)
        self.checkModified.setObjectName("checkModified")
        self.verticalLayout_3.addWidget(self.checkModified)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.comboGarage = QtWidgets.QComboBox(DialogVehicleEdit)
        self.comboGarage.setObjectName("comboGarage")
        self.verticalLayout_4.addWidget(self.comboGarage)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushOk = QtWidgets.QPushButton(DialogVehicleEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushOk.sizePolicy().hasHeightForWidth())
        self.pushOk.setSizePolicy(sizePolicy)
        self.pushOk.setMinimumSize(QtCore.QSize(85, 27))
        self.pushOk.setMaximumSize(QtCore.QSize(85, 27))
        self.pushOk.setSizeIncrement(QtCore.QSize(85, 27))
        self.pushOk.setBaseSize(QtCore.QSize(85, 27))
        self.pushOk.setObjectName("pushOk")
        self.horizontalLayout_2.addWidget(self.pushOk)
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushCancel = QtWidgets.QPushButton(DialogVehicleEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushCancel.sizePolicy().hasHeightForWidth())
        self.pushCancel.setSizePolicy(sizePolicy)
        self.pushCancel.setMinimumSize(QtCore.QSize(85, 27))
        self.pushCancel.setMaximumSize(QtCore.QSize(85, 27))
        self.pushCancel.setSizeIncrement(QtCore.QSize(85, 27))
        self.pushCancel.setBaseSize(QtCore.QSize(85, 27))
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_2.addWidget(self.pushCancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(DialogVehicleEdit)
        QtCore.QMetaObject.connectSlotsByName(DialogVehicleEdit)

    def retranslateUi(self, DialogVehicleEdit):
        _translate = QtCore.QCoreApplication.translate
        DialogVehicleEdit.setWindowTitle(_translate("DialogVehicleEdit", "Vehicle Editor"))
        self.checkWishlist.setText(_translate("DialogVehicleEdit", "Wishlist"))
        self.checkPegasus.setText(_translate("DialogVehicleEdit", "Pegasus"))
        self.checkOwned.setText(_translate("DialogVehicleEdit", "Owned"))
        self.checkDelete.setText(_translate("DialogVehicleEdit", "Delete"))
        self.checkInsured.setText(_translate("DialogVehicleEdit", "Insured"))
        self.checkModified.setText(_translate("DialogVehicleEdit", "Full Mod"))
        self.pushOk.setText(_translate("DialogVehicleEdit", "Ok"))
        self.pushCancel.setText(_translate("DialogVehicleEdit", "Cancel"))
