# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI Files/vehicle_add.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogVehicleAdd(object):
    def setupUi(self, DialogVehicleAdd):
        DialogVehicleAdd.setObjectName("DialogVehicleAdd")
        DialogVehicleAdd.resize(458, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogVehicleAdd.sizePolicy().hasHeightForWidth())
        DialogVehicleAdd.setSizePolicy(sizePolicy)
        DialogVehicleAdd.setMinimumSize(QtCore.QSize(458, 200))
        DialogVehicleAdd.setMaximumSize(QtCore.QSize(458, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GarageTracker.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogVehicleAdd.setWindowIcon(icon)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(DialogVehicleAdd)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkWishlist = QtWidgets.QCheckBox(DialogVehicleAdd)
        self.checkWishlist.setObjectName("checkWishlist")
        self.verticalLayout.addWidget(self.checkWishlist)
        self.checkPegasus = QtWidgets.QCheckBox(DialogVehicleAdd)
        self.checkPegasus.setObjectName("checkPegasus")
        self.verticalLayout.addWidget(self.checkPegasus)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkOwned = QtWidgets.QCheckBox(DialogVehicleAdd)
        self.checkOwned.setObjectName("checkOwned")
        self.verticalLayout_2.addWidget(self.checkOwned)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkInsured = QtWidgets.QCheckBox(DialogVehicleAdd)
        self.checkInsured.setObjectName("checkInsured")
        self.verticalLayout_3.addWidget(self.checkInsured)
        self.checkModified = QtWidgets.QCheckBox(DialogVehicleAdd)
        self.checkModified.setObjectName("checkModified")
        self.verticalLayout_3.addWidget(self.checkModified)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(DialogVehicleAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(101, 22))
        self.label.setMaximumSize(QtCore.QSize(101, 22))
        self.label.setBaseSize(QtCore.QSize(101, 22))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineName = QtWidgets.QLineEdit(DialogVehicleAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineName.sizePolicy().hasHeightForWidth())
        self.lineName.setSizePolicy(sizePolicy)
        self.lineName.setMinimumSize(QtCore.QSize(0, 22))
        self.lineName.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lineName.setBaseSize(QtCore.QSize(0, 22))
        self.lineName.setObjectName("lineName")
        self.horizontalLayout_3.addWidget(self.lineName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.comboClass = QtWidgets.QComboBox(DialogVehicleAdd)
        self.comboClass.setObjectName("comboClass")
        self.verticalLayout_4.addWidget(self.comboClass)
        self.comboGarage = QtWidgets.QComboBox(DialogVehicleAdd)
        self.comboGarage.setObjectName("comboGarage")
        self.verticalLayout_4.addWidget(self.comboGarage)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushOk = QtWidgets.QPushButton(DialogVehicleAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushOk.sizePolicy().hasHeightForWidth())
        self.pushOk.setSizePolicy(sizePolicy)
        self.pushOk.setMinimumSize(QtCore.QSize(85, 27))
        self.pushOk.setMaximumSize(QtCore.QSize(85, 27))
        self.pushOk.setSizeIncrement(QtCore.QSize(85, 27))
        self.pushOk.setBaseSize(QtCore.QSize(85, 27))
        self.pushOk.setObjectName("pushOk")
        self.horizontalLayout_2.addWidget(self.pushOk)
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushCancel = QtWidgets.QPushButton(DialogVehicleAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushCancel.sizePolicy().hasHeightForWidth())
        self.pushCancel.setSizePolicy(sizePolicy)
        self.pushCancel.setMinimumSize(QtCore.QSize(85, 27))
        self.pushCancel.setMaximumSize(QtCore.QSize(85, 27))
        self.pushCancel.setSizeIncrement(QtCore.QSize(85, 27))
        self.pushCancel.setBaseSize(QtCore.QSize(85, 27))
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_2.addWidget(self.pushCancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(DialogVehicleAdd)
        QtCore.QMetaObject.connectSlotsByName(DialogVehicleAdd)

    def retranslateUi(self, DialogVehicleAdd):
        _translate = QtCore.QCoreApplication.translate
        DialogVehicleAdd.setWindowTitle(_translate("DialogVehicleAdd", "Add A Vehicle"))
        self.checkWishlist.setText(_translate("DialogVehicleAdd", "Wishlist"))
        self.checkPegasus.setText(_translate("DialogVehicleAdd", "Pegasus"))
        self.checkOwned.setText(_translate("DialogVehicleAdd", "Owned"))
        self.checkInsured.setText(_translate("DialogVehicleAdd", "Insured"))
        self.checkModified.setText(_translate("DialogVehicleAdd", "Full Mod"))
        self.label.setText(_translate("DialogVehicleAdd", "Vehicle Name"))
        self.pushOk.setText(_translate("DialogVehicleAdd", "Ok"))
        self.pushCancel.setText(_translate("DialogVehicleAdd", "Cancel"))
