# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI Files/vehicle_warehouse_checklist.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VWChecklist(object):
    def setupUi(self, VWChecklist):
        VWChecklist.setObjectName("VWChecklist")
        VWChecklist.resize(497, 462)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(VWChecklist)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(VWChecklist)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(VWChecklist)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(VWChecklist)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkAlpha = QtWidgets.QCheckBox(VWChecklist)
        self.checkAlpha.setTristate(False)
        self.checkAlpha.setObjectName("checkAlpha")
        self.verticalLayout_3.addWidget(self.checkAlpha)
        self.checkBanshee900R = QtWidgets.QCheckBox(VWChecklist)
        self.checkBanshee900R.setTristate(False)
        self.checkBanshee900R.setObjectName("checkBanshee900R")
        self.verticalLayout_3.addWidget(self.checkBanshee900R)
        self.checkBestiaGTS = QtWidgets.QCheckBox(VWChecklist)
        self.checkBestiaGTS.setTristate(False)
        self.checkBestiaGTS.setObjectName("checkBestiaGTS")
        self.verticalLayout_3.addWidget(self.checkBestiaGTS)
        self.checkFeltzer = QtWidgets.QCheckBox(VWChecklist)
        self.checkFeltzer.setTristate(False)
        self.checkFeltzer.setObjectName("checkFeltzer")
        self.verticalLayout_3.addWidget(self.checkFeltzer)
        self.checkJester = QtWidgets.QCheckBox(VWChecklist)
        self.checkJester.setTristate(False)
        self.checkJester.setObjectName("checkJester")
        self.verticalLayout_3.addWidget(self.checkJester)
        self.checkMassacro = QtWidgets.QCheckBox(VWChecklist)
        self.checkMassacro.setTristate(False)
        self.checkMassacro.setObjectName("checkMassacro")
        self.verticalLayout_3.addWidget(self.checkMassacro)
        self.checkNightshade = QtWidgets.QCheckBox(VWChecklist)
        self.checkNightshade.setTristate(False)
        self.checkNightshade.setObjectName("checkNightshade")
        self.verticalLayout_3.addWidget(self.checkNightshade)
        self.checkSabreTurboCustom = QtWidgets.QCheckBox(VWChecklist)
        self.checkSabreTurboCustom.setTristate(False)
        self.checkSabreTurboCustom.setObjectName("checkSabreTurboCustom")
        self.verticalLayout_3.addWidget(self.checkSabreTurboCustom)
        self.checkTampa = QtWidgets.QCheckBox(VWChecklist)
        self.checkTampa.setTristate(False)
        self.checkTampa.setObjectName("checkTampa")
        self.verticalLayout_3.addWidget(self.checkTampa)
        self.checkTurismoR = QtWidgets.QCheckBox(VWChecklist)
        self.checkTurismoR.setTristate(False)
        self.checkTurismoR.setObjectName("checkTurismoR")
        self.verticalLayout_3.addWidget(self.checkTurismoR)
        self.label_3 = QtWidgets.QLabel(VWChecklist)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(VWChecklist)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_8 = QtWidgets.QLabel(VWChecklist)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkCheetah = QtWidgets.QCheckBox(VWChecklist)
        self.checkCheetah.setTristate(False)
        self.checkCheetah.setObjectName("checkCheetah")
        self.verticalLayout_2.addWidget(self.checkCheetah)
        self.checkCoquetteBlackFin = QtWidgets.QCheckBox(VWChecklist)
        self.checkCoquetteBlackFin.setTristate(False)
        self.checkCoquetteBlackFin.setObjectName("checkCoquetteBlackFin")
        self.verticalLayout_2.addWidget(self.checkCoquetteBlackFin)
        self.checkCoquetteClassic = QtWidgets.QCheckBox(VWChecklist)
        self.checkCoquetteClassic.setTristate(False)
        self.checkCoquetteClassic.setObjectName("checkCoquetteClassic")
        self.verticalLayout_2.addWidget(self.checkCoquetteClassic)
        self.checkEntityXF = QtWidgets.QCheckBox(VWChecklist)
        self.checkEntityXF.setTristate(False)
        self.checkEntityXF.setObjectName("checkEntityXF")
        self.verticalLayout_2.addWidget(self.checkEntityXF)
        self.checkOmnis = QtWidgets.QCheckBox(VWChecklist)
        self.checkOmnis.setTristate(False)
        self.checkOmnis.setObjectName("checkOmnis")
        self.verticalLayout_2.addWidget(self.checkOmnis)
        self.checkSeven70 = QtWidgets.QCheckBox(VWChecklist)
        self.checkSeven70.setTristate(False)
        self.checkSeven70.setObjectName("checkSeven70")
        self.verticalLayout_2.addWidget(self.checkSeven70)
        self.checkSultanRS = QtWidgets.QCheckBox(VWChecklist)
        self.checkSultanRS.setTristate(False)
        self.checkSultanRS.setObjectName("checkSultanRS")
        self.verticalLayout_2.addWidget(self.checkSultanRS)
        self.checkTroposRallye = QtWidgets.QCheckBox(VWChecklist)
        self.checkTroposRallye.setTristate(False)
        self.checkTroposRallye.setObjectName("checkTroposRallye")
        self.verticalLayout_2.addWidget(self.checkTroposRallye)
        self.checkVerlierer = QtWidgets.QCheckBox(VWChecklist)
        self.checkVerlierer.setTristate(False)
        self.checkVerlierer.setObjectName("checkVerlierer")
        self.verticalLayout_2.addWidget(self.checkVerlierer)
        self.checkZentorno = QtWidgets.QCheckBox(VWChecklist)
        self.checkZentorno.setTristate(False)
        self.checkZentorno.setObjectName("checkZentorno")
        self.verticalLayout_2.addWidget(self.checkZentorno)
        self.label_5 = QtWidgets.QLabel(VWChecklist)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(VWChecklist)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(VWChecklist)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.check811 = QtWidgets.QCheckBox(VWChecklist)
        self.check811.setTristate(False)
        self.check811.setObjectName("check811")
        self.verticalLayout.addWidget(self.check811)
        self.checkETR1 = QtWidgets.QCheckBox(VWChecklist)
        self.checkETR1.setTristate(False)
        self.checkETR1.setObjectName("checkETR1")
        self.verticalLayout.addWidget(self.checkETR1)
        self.checkFMJ = QtWidgets.QCheckBox(VWChecklist)
        self.checkFMJ.setTristate(False)
        self.checkFMJ.setObjectName("checkFMJ")
        self.verticalLayout.addWidget(self.checkFMJ)
        self.checkMamba = QtWidgets.QCheckBox(VWChecklist)
        self.checkMamba.setTristate(False)
        self.checkMamba.setObjectName("checkMamba")
        self.verticalLayout.addWidget(self.checkMamba)
        self.checkOsiris = QtWidgets.QCheckBox(VWChecklist)
        self.checkOsiris.setTristate(False)
        self.checkOsiris.setObjectName("checkOsiris")
        self.verticalLayout.addWidget(self.checkOsiris)
        self.checkReaper = QtWidgets.QCheckBox(VWChecklist)
        self.checkReaper.setTristate(False)
        self.checkReaper.setObjectName("checkReaper")
        self.verticalLayout.addWidget(self.checkReaper)
        self.checkRooseveltValor = QtWidgets.QCheckBox(VWChecklist)
        self.checkRooseveltValor.setTristate(False)
        self.checkRooseveltValor.setObjectName("checkRooseveltValor")
        self.verticalLayout.addWidget(self.checkRooseveltValor)
        self.checkStirlingGT = QtWidgets.QCheckBox(VWChecklist)
        self.checkStirlingGT.setTristate(False)
        self.checkStirlingGT.setObjectName("checkStirlingGT")
        self.verticalLayout.addWidget(self.checkStirlingGT)
        self.checkT20 = QtWidgets.QCheckBox(VWChecklist)
        self.checkT20.setTristate(False)
        self.checkT20.setObjectName("checkT20")
        self.verticalLayout.addWidget(self.checkT20)
        self.checkTyrus = QtWidgets.QCheckBox(VWChecklist)
        self.checkTyrus.setTristate(False)
        self.checkTyrus.setObjectName("checkTyrus")
        self.verticalLayout.addWidget(self.checkTyrus)
        self.checkX80Proto = QtWidgets.QCheckBox(VWChecklist)
        self.checkX80Proto.setTristate(False)
        self.checkX80Proto.setObjectName("checkX80Proto")
        self.verticalLayout.addWidget(self.checkX80Proto)
        self.checkZType = QtWidgets.QCheckBox(VWChecklist)
        self.checkZType.setTristate(False)
        self.checkZType.setObjectName("checkZType")
        self.verticalLayout.addWidget(self.checkZType)
        self.label_10 = QtWidgets.QLabel(VWChecklist)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(VWChecklist)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushCancel = QtWidgets.QPushButton(VWChecklist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushCancel.sizePolicy().hasHeightForWidth())
        self.pushCancel.setSizePolicy(sizePolicy)
        self.pushCancel.setMinimumSize(QtCore.QSize(95, 27))
        self.pushCancel.setMaximumSize(QtCore.QSize(95, 27))
        self.pushCancel.setBaseSize(QtCore.QSize(95, 27))
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_3.addWidget(self.pushCancel)
        spacerItem = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushOk = QtWidgets.QPushButton(VWChecklist)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushOk.sizePolicy().hasHeightForWidth())
        self.pushOk.setSizePolicy(sizePolicy)
        self.pushOk.setMinimumSize(QtCore.QSize(95, 27))
        self.pushOk.setMaximumSize(QtCore.QSize(95, 27))
        self.pushOk.setBaseSize(QtCore.QSize(95, 27))
        self.pushOk.setObjectName("pushOk")
        self.horizontalLayout_3.addWidget(self.pushOk)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)

        self.retranslateUi(VWChecklist)
        QtCore.QMetaObject.connectSlotsByName(VWChecklist)

    def retranslateUi(self, VWChecklist):
        _translate = QtCore.QCoreApplication.translate
        VWChecklist.setWindowTitle(_translate("VWChecklist", "Form"))
        self.label.setText(_translate("VWChecklist", "Standard"))
        self.label_2.setText(_translate("VWChecklist", "Mid"))
        self.label_7.setText(_translate("VWChecklist", "Top"))
        self.checkAlpha.setText(_translate("VWChecklist", "Alpha"))
        self.checkBanshee900R.setText(_translate("VWChecklist", "Banshee 900R"))
        self.checkBestiaGTS.setText(_translate("VWChecklist", "Bestia GTS"))
        self.checkFeltzer.setText(_translate("VWChecklist", "Feltzer"))
        self.checkJester.setText(_translate("VWChecklist", "Jester"))
        self.checkMassacro.setText(_translate("VWChecklist", "Massacro"))
        self.checkNightshade.setText(_translate("VWChecklist", "Nightshade"))
        self.checkSabreTurboCustom.setText(_translate("VWChecklist", "Sabre Turbo Custom"))
        self.checkTampa.setText(_translate("VWChecklist", "Tampa"))
        self.checkTurismoR.setText(_translate("VWChecklist", "Turismo R"))
        self.checkCheetah.setText(_translate("VWChecklist", "Cheetah"))
        self.checkCoquetteBlackFin.setText(_translate("VWChecklist", "Coquette BlackFin"))
        self.checkCoquetteClassic.setText(_translate("VWChecklist", "Coquette Classic"))
        self.checkEntityXF.setText(_translate("VWChecklist", "Entity XF"))
        self.checkOmnis.setText(_translate("VWChecklist", "Omnis"))
        self.checkSeven70.setText(_translate("VWChecklist", "Seven-70"))
        self.checkSultanRS.setText(_translate("VWChecklist", "Sultan RS"))
        self.checkTroposRallye.setText(_translate("VWChecklist", "Tropos Rallye"))
        self.checkVerlierer.setText(_translate("VWChecklist", "Verlierer"))
        self.checkZentorno.setText(_translate("VWChecklist", "Zentorno"))
        self.check811.setText(_translate("VWChecklist", "811"))
        self.checkETR1.setText(_translate("VWChecklist", "ETR1"))
        self.checkFMJ.setText(_translate("VWChecklist", "FMJ"))
        self.checkMamba.setText(_translate("VWChecklist", "Mamba"))
        self.checkOsiris.setText(_translate("VWChecklist", "Osiris"))
        self.checkReaper.setText(_translate("VWChecklist", "Reaper"))
        self.checkRooseveltValor.setText(_translate("VWChecklist", "Roosevelt Valor"))
        self.checkStirlingGT.setText(_translate("VWChecklist", "Stirling GT"))
        self.checkT20.setText(_translate("VWChecklist", "T20"))
        self.checkTyrus.setText(_translate("VWChecklist", "Tyrus"))
        self.checkX80Proto.setText(_translate("VWChecklist", "X80 Proto"))
        self.checkZType.setText(_translate("VWChecklist", "Z-Type"))
        self.pushCancel.setText(_translate("VWChecklist", "Cancel"))
        self.pushOk.setText(_translate("VWChecklist", "Ok"))
